version: '3.4'

services:

  base:
    container_name: ${COMPOSE_PROJECT_NAME}_base
    image: ${COMPOSE_PROJECT_NAME}_base
    build:
      context: docker/base/php
      args:
        COMPOSE_UID: ${COMPOSE_UID}
        COMPOSE_GID: ${COMPOSE_GID}
    entrypoint: /bin/bash

  dev:
    container_name: ${COMPOSE_PROJECT_NAME}_dev
    build:
      context: docker/dev/php
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - 80:8080
    environment:
      APP_ENV: dev
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/dev/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/dev/php/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - base

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: mariadb:10.2.19
    environment:
      MYSQL_ROOT_PASSWORD: nimesaleries
      MYSQL_DATABASE: nimesaleries
      MYSQL_USER: nimesaleries
      MYSQL_PASSWORD: nimesaleries
    volumes:
      - db_data:/var/lib/mysql

  pma:
    container_name: ${COMPOSE_PROJECT_NAME}_pma
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db

volumes:

  db_data:
    name: ${COMPOSE_PROJECT_NAME}_db_data
